### ISSUE TITLE
Napisati izveštaj za 1. sedmicu

### ISSUE THREAD

**Issue by ajzenhamernikola** [MATF-RS20/RS026-audio-mikseta#1]

**Comment by ngaCungaLu** [comment]
Postavljanje projekta, kreiranje glavnog prozora i povezivanje sa audio thread-om. 
Glavni prozor:
-MainComponent.h
-MainComponent.cpp
Sadrzace sve ostale GUI komponente i procesiranje audio signala.
-Main.cpp
Sadrzi klase i funkcije za kreiranje i prikazivanje glavnog GUI prozora.

-Kreiranje nove klase FileExplorer
FileExplorer je GUI komponenta cija funkcija je da ucitava neki folder i izlistava njegovu strukturu. Folder se ubacuje pomocu Drag and Drop-a.
U strukturi bice prikazani samo oni fajlovi koji imaju ekstenziju .wav jer su samo oni od interesa.
-U MainComponent je dodat objekat klase FileExplorer.

-Kreiranje klase DeckPanel kao osnovne komponente za rad miksera. Jedna od funkcionalnosti klase je da ucitava .wav fajl pomocu
Drag And Drop-a. Fajl moze biti direktno prevucen iz FileExplorera ili iz nekog drugog foldera u sistemu.
Cilj DeckPanel klase je da reprodukuje audio fajl koji je prethodno ucitan i nad njim vrsi neku obradu audio signala.
Trenutne opcije su:Play, Pause, Stop, Loop.
-Klasa WaveformDisplay iscrtava audio signal iz ucitanog fajla.
DeckPanel poseduje jedan objekat klase WaveformDisplay.

MainComponent poseduje dva objekta klase DeckPanel, i klizac koji se nalazi izmedju njih koji definise nivo mesanja zvuka koji 
potice iz oba DeckPanel-a.

**Comment by ajzenhamernikola** [comment]
@ngaCungaLu, molim Vas da kreirate Wiki stranicu za izvestaj, pa zatvorite primedbu kad zavrsite
